services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: stats
      POSTGRES_USER: stats
      POSTGRES_DB: ewm-stats
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
      interval: 5s
      retries: 10

  stats-service:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    healthcheck:
      test: curl --fail http://localhost:9090/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:16.1
    container_name: postgres-main
    ports:
      - "6542:5432"
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: ewm-main
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-main
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/ewm-main
      SPRING_DATASOURCE_USERNAME: main
      SPRING_DATASOURCE_PASSWORD: main
    healthcheck:
      test: curl --fail http://localhost:9090/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5